# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4706df9f6e5b05293aa5a57c457e6cc014cafc48f506605acd0a5ea909db67ebc1427f34cb796e27ac6f8962d2c1a81416427b50ebe54202f95cf37c12760319

test:
  secret_key_base: 57e853803758d2d04031b3764adcfb9503ecb5424b32ba4f86edecca8103989725d145f50ade2c06204736f4800917e28d2f1484a635e0e127560b330eff138a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
